### ISSUE TITLE
Abandon PHP for ECMAScript

### ISSUE THREAD

**Issue by RGustBardon** [MinifyJS/MinifyJS#19]
Since MinifyJS transforms ECMAScript, it could be argued that the tool's users are more likely to program in ECMAScript than in PHP. If PHP is abandoned for ECMAScript:
- [V8](https://code.google.com/p/v8/) could be used to execute the code;
- the original version of the [Narcissus](https://github.com/mozilla/narcissus/) which is available on GitHuB could be used which, since it is developed by Mozilla, is more likely to be thoroughly tested, supported, and introduce support for next editions of ECMAScript;
- Narcissus could be replaced by [Esprima](http://esprima.org/) which is a much faster parser (cf. http://esprima.org/test/compare.html);
- tools such as [falafel](https://github.com/substack/node-falafel) could be used to transform the AST;
- [escodegen](https://github.com/Constellation/escodegen) could either be forked or developed to generate code;
- the project could be distributed as an [npm](http://npmjs.org/) package and a replacement for [UglifyJS](https://github.com/mishoo/UglifyJS).

In the context of transforming an AST representing an ECMAScript program, what are the advantages of PHP and its standards library in comparison to ECMAScript? [Execution speed is comparable](http://shootout.alioth.debian.org/u32/benchmark.php?test=all&lang=php&lang2=v8).

Not to suggest that the popularity of PHP is on a par with Common Lisp, one could compare the number of issues and pull request of the [Common Lisp](https://github.com/mishoo/cl-uglify-js) and the [ECMAScript](https://github.com/mishoo/UglifyJS) versions of UglifyJS.

PHP support could be provided as a language binding.

**Comment by rvanvelzen** [comment]
One could argue that JavaScript would be more appropriate than PHP for transforming JavaScript programs. However, this project was specifically meant to be written in PHP. A seperate project in JavaScript, using (amongst others) the tools you named could be worth the time, but this project will remain a PHP project.

All that aside, I much appreciate all the issues you filed. I will look at them in the following days. :-)
