### ISSUE TITLE
Establish a dedicated GitHub organization

### ISSUE THREAD

**Issue by RGustBardon** [MinifyJS/MinifyJS#20]
Since the project be related to other projects (a Web application, a Web service, forked or frozen dependencies) in the future, one could think of creating a dedicated GitHub organization for the project. It could then be easier to find all related projects in one place (cf. [jQuery](https://github.com/jquery), [Symfony](https://github.com/symfony), etc.). Moreover, external developers could prefer contributing to a repository such as https://github.com/bazola/bazola over https://github.com/johnbloggs/bazola/.

**Comment by rvanvelzen** [comment]
Done. :-)
